services:
  - type: web
    name: safehaven-backend
    runtime: python
    rootDir: server
    buildCommand: "./build.sh"
    startCommand: "cd src && pipenv run gunicorn mindvoice_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
