[phases.setup]
nixPkgs = ["python312", "pipenv"]

[phases.install]
cmds = ["pipenv install --deploy"]

[phases.build]
cmds = ["cd src && pipenv run python manage.py collectstatic --no-input"]

[start]
cmd = "cd src && pipenv run gunicorn mindvoice_project.wsgi:application --bind 0.0.0.0:$PORT"
